In [1]:
!git clone https://github.com/yumelab-studio/avaia-seismofinance.git

Cloning into 'avaia-seismofinance'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 27 (delta 7), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (27/27), 76.34 KiB | 2.54 MiB/s, done.
Resolving deltas: 100% (7/7), done.

In [2]:
import os
os.chdir('avaia-seismofinance')

In [6]:
import pandas as pd

df_eq=pd.read_csv('data/raw/earthquake.csv')
df_eq.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2026-04-04T10:36:46.191Z,38.4373,141.9269,67.953,5.0,mb,43.0,94.0,2.442,1.03,...,2026-04-04T10:58:55.040Z,"41 km E of Onagawa Chō, Japan",earthquake,7.46,7.045,0.031,334.0,reviewed,us,us
1,2026-04-02T00:52:52.373Z,38.1670,141.6037,66.591,5.0,mb,58.0,128.0,2.652,0.55,...,2026-04-03T00:41:21.454Z,"33 km SSE of Onagawa Chō, Japan",earthquake,16.88,21.079,0.060,88.0,reviewed,us,us
2,2026-03-27T15:24:33.227Z,39.3975,143.1958,16.096,5.1,mb,55.0,135.0,2.146,1.01,...,2026-03-27T15:39:29.040Z,"107 km E of Yamada, Japan",earthquake,7.86,5.085,0.062,83.0,reviewed,us,us
3,2026-03-26T14:18:50.947Z,39.4462,143.3717,9.513,6.5,mww,121.0,45.0,2.220,0.82,...,2026-03-27T14:47:28.298Z,"122 km E of Yamada, Japan",earthquake,6.84,4.170,0.038,66.0,reviewed,us,us
4,2026-03-21T11:12:04.314Z,29.4858,130.6689,21.650,5.4,mww,98.0,110.0,2.025,0.87,...,2026-04-02T11:41:55.694Z,"84 km S of Koshima, Japan",earthquake,6.94,4.967,0.063,24.0,reviewed,us,us

In [7]:
df_eq = df_eq[['time', 'mag', 'place']]

In [8]:
df_eq = df_eq.rename(columns={
    'time': 'date',
    'mag': 'magnitude'
})

In [9]:
df_eq['date'] = pd.to_datetime(df_eq['date'])

In [10]:
df_eq = df_eq[df_eq['magnitude'] >= 5]

In [11]:
df_eq = df_eq.sort_values(by='date')

In [13]:
df_eq.to_csv('results/earthquakes_clean.csv', index=False)

In [17]:
#check
df_check = pd.read_csv('results/earthquakes_clean.csv')
df_check.head()

                               date  magnitude                           place
0  2011-04-06 13:54:52.200000+00:00        5.3       42 km ENE of Namie, Japan
1  2011-04-07 14:32:43.290000+00:00        7.1  29 km ESE of Ishinomaki, Japan
2  2011-04-07 22:02:19.880000+00:00        5.1      88 km ESE of Yamada, Japan
3  2011-04-09 01:25:26.660000+00:00        5.1      109 km ESE of Iwaki, Japan
4  2011-04-09 09:42:21.890000+00:00        5.3  38 km ESE of Ishinomaki, Japan